/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ../../public/models/ferrari.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ferrari.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.676, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]}>
        <mesh geometry={nodes.trim.geometry} material={materials.Leather_red} position={[-0.379, -0.004, -0.016]} />
        <mesh geometry={nodes.lights_red.geometry} material={materials.Taillight_Glass} position={[0.913, -0.004, -0.006]} />
        <mesh geometry={nodes.plastic_gray.geometry} material={materials.plastic_gray} position={[0.108, -0.001, -0.029]} />
        <mesh geometry={nodes.metal.geometry} material={materials.metal_gray} position={[0.218, -0.005, -0.002]} />
        <mesh geometry={nodes.lights.geometry} material={materials.Projector_Glass} position={[-1.845, -0.002, -0.067]} />
        <mesh geometry={nodes.leds.geometry} material={materials.Turn_Signal_LED} position={[-1.265, -0.001, 0.022]} />
        <mesh geometry={nodes.leather.geometry} material={materials.Leather} position={[-0.348, -0.002, -0.031]} />
        <mesh geometry={nodes.interior_light.geometry} material={materials.Interior_dark} position={[0.005, -0.004, -0.004]} />
        <mesh geometry={nodes.grills.geometry} material={materials.Tires} position={[0.048, -0.007, -0.033]} />
        <mesh geometry={nodes.glass.geometry} material={materials.Glass_Gray} position={[0.001, -0.002, 0.194]} />
        <mesh geometry={nodes.chrome.geometry} material={materials.metal_chrome} position={[0.033, 0, 0.007]} />
        <mesh geometry={nodes.carpet.geometry} material={materials.Carpet} position={[-0.281, -0.004, -0.235]} />
        <mesh geometry={nodes.carbon_fibre_trim.geometry} material={materials.Carbon_Fiber} position={[-0.177, -0.002, -0.04]} />
        <mesh geometry={nodes.carbon_fibre.geometry} material={materials.Carbon_Fiber} position={[-0.438, -0.346, 0.118]} />
        <mesh geometry={nodes.brakes.geometry} material={materials.Taillight_Glass} position={[1.989, -0.004, 0.2]} />
        <mesh geometry={nodes.interior_dark.geometry} material={materials.Interior_light} position={[0.003, 0, 0.011]} />
        <mesh geometry={nodes.body.geometry} material={materials.Body_Color} position={[-0.005, 0, 0.022]} />
        <mesh geometry={nodes.blue.geometry} material={materials._0098_DodgerBlue} position={[-0.35, -0.435, 0.068]} />
        <mesh geometry={nodes.wipers.geometry} material={materials.Tires} position={[-1.089, 0.006, 0.11]} />
        <mesh geometry={nodes.yellow_trim.geometry} material={materials.Ferrari_Yellow} position={[-1.397, -0.003, 0.047]} />
      </group>
      <group position={[0.824, 0.358, 1.496]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.wheel.geometry} material={materials.metal_gray} position={[0, 0, -0.001]} />
        <mesh geometry={nodes.tire.geometry} material={materials.Tires} position={[-0.005, 0, 0]} />
        <mesh geometry={nodes.rim_rr.geometry} material={materials.metal_gray} position={[0.125, 0, -0.001]} />
        <mesh geometry={nodes.centre.geometry} material={materials.Ferrari_Yellow} position={[0.113, 0, -0.001]} />
        <mesh geometry={nodes.brake.geometry} material={materials.metal_gray} position={[0.009, 0.001, -0.001]} />
        <mesh geometry={nodes.nuts.geometry} material={materials.Interior_dark} position={[0.103, 0, 0.006]} />
      </group>
      <group position={[-0.821, 0.358, 1.495]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.tire_1.geometry} material={materials.Tires} position={[0.006, 0, 0]} />
        <mesh geometry={nodes.brake_1.geometry} material={materials.metal_gray} position={[-0.018, -0.001, -0.001]} />
        <mesh geometry={nodes.centre_1.geometry} material={materials.Ferrari_Yellow} position={[-0.113, 0, -0.001]} />
        <mesh geometry={nodes.wheel_1.geometry} material={materials.metal_gray} position={[0, 0, -0.001]} />
        <mesh geometry={nodes.rim_rl.geometry} material={materials.metal_gray} position={[-0.125, 0, -0.001]} />
        <mesh geometry={nodes.nuts_1.geometry} material={materials.Interior_dark} position={[-0.103, 0, 0.006]} />
      </group>
      <group position={[-0.843, 0.358, -1.155]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.rim_fl.geometry} material={materials.metal_gray} position={[-0.114, 0, -0.001]} />
        <mesh geometry={nodes.brake_2.geometry} material={materials.metal_gray} position={[-0.002, -0.001, -0.001]} />
        <mesh geometry={nodes.centre_2.geometry} material={materials.Ferrari_Yellow} position={[-0.102, 0, -0.001]} />
        <mesh geometry={nodes.nuts_2.geometry} material={materials.Interior_dark} position={[-0.094, 0, 0.006]} />
        <mesh geometry={nodes.wheel_2.geometry} material={materials.metal_gray} position={[0, 0, -0.001]} />
        <mesh geometry={nodes.tire_2.geometry} material={materials.Tires} position={[0.005, 0, 0]} />
      </group>
      <group position={[0.829, 0.361, -1.154]} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.brake_3.geometry} material={materials.metal_gray} position={[0.001, 0, -0.001]} />
        <mesh geometry={nodes.centre_3.geometry} material={materials.Ferrari_Yellow} position={[0.102, 0, -0.001]} />
        <mesh geometry={nodes.wheel_3.geometry} material={materials.metal_gray} position={[0, 0, -0.001]} />
        <mesh geometry={nodes.rim_fr.geometry} material={materials.metal_gray} position={[0.114, 0, -0.001]} />
        <mesh geometry={nodes.tire_3.geometry} material={materials.Tires} position={[-0.005, 0, 0]} />
        <mesh geometry={nodes.nuts_3.geometry} material={materials.Interior_dark} position={[0.094, 0, 0.006]} />
      </group>
      <group position={[-0.346, 0.799, -0.346]} rotation={[-1.92, 0, 0]}>
        <mesh geometry={nodes.steering_carbon.geometry} material={materials.Carbon_Fiber} position={[0, 0.016, 0.006]} rotation={[Math.PI / 9, 0, 0]} />
        <mesh geometry={nodes.steering_centre.geometry} material={materials.Ferrari_Yellow} />
        <mesh geometry={nodes.steering_column.geometry} material={materials.Interior_dark} position={[0, 0.068, -0.015]} rotation={[Math.PI / 9, 0, 0]} />
        <mesh geometry={nodes.steering_leather.geometry} material={materials.Leather} position={[0, 0.015, 0.007]} rotation={[Math.PI / 9, 0, 0]} />
        <mesh geometry={nodes.steering_metal.geometry} material={materials.metal_gray} position={[0.086, 0.021, -0.066]} rotation={[Math.PI / 9, 0, 0]} />
        <mesh geometry={nodes.steering_red_lights.geometry} material={materials.Taillight_Glass} position={[0.006, 0.02, -0.072]} rotation={[Math.PI / 9, 0, 0]} />
        <mesh geometry={nodes.steering_trim.geometry} material={materials.Leather_red} position={[0, 0.016, -0.075]} rotation={[Math.PI / 9, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/ferrari.glb')
